name: Create the Azure Infrastructure for the Cloud Positive Website
on:
    push:
        branches: [ main, feature/* ]
    workflow_dispatch:

jobs:
    terraform-plan:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        defaults:
          run:
            working-directory: .

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - uses: azure/login@v1
              name: Azure OIDC login
              with:         
                tenant-id: ${{ secrets.TENANT_ID }}
                client-id: ${{ secrets.CLIENT_ID }}
                subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
                enable-AzPSSession: true
            
            - uses: hashicorp/setup-terraform@v3
              with:
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

            - run: terraform init

            - run: terraform plan
    
    terraform-apply:
        runs-on: ubuntu-latest
        needs: terraform-plan
        environment: "p"
        if: success() # Only proceed if terraform-plan job succeeds
        
        permissions:
            contents: read
            id-token: write
        defaults:
          run:
            working-directory: .

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - uses: azure/login@v1
              name: Azure OIDC login
              with:         
                tenant-id: ${{ secrets.TENANT_ID }}
                client-id: ${{ secrets.CLIENT_ID }}
                subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
                enable-AzPSSession: true
            
            - uses: hashicorp/setup-terraform@v3
              with:
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

            - run: terraform init
            - run: terraform apply -auto-approve