name: Create the Azure Infrastructure for the Cloud Positive Website
on:
    push:
        branches: [ main, feature/* ]
    workflow_dispatch:

jobs:
    azure-infrastructure-foundation:
        runs-on: [Linux]
        permissions:
            contents: read
            id-token: write
        
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - uses: azure/login@v1
              name: Azure OIDC login
              with:         
                tenant-id: ${{ secrets.TENANT_ID }}
                client-id: ${{ secrets.CLIENT_ID }}
                subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
                enable-AzPSSession: true
            
            - uses: bash
              name: Terraform Login
              with:
                script: |
                  export TF_TOKEN_app_terraform_io="${{ secrets.TF_API_TOKEN }}"
                  echo "Terraform login successful"

            - uses: bash
              name: Terraform initialize
              with:
                script: |
                  terraform init